import pandas as pd 
import matplotlib.pyplot as plt 
df = pd.read_csv('E:\csvdhf5xlsxurlallfiles/percent-bachelors-degrees-women-usa.csv')
print(df.head())
print(df.columns)
year=df['Year']
plysical_science=df['Physical Sciences']
computer_science=df['Computer Science']
plt.plot(year, plysical_science, color='blue')
plt.plot(year, computer_science, color='red')
plt.show()
plt.axes([0.05,0.05,0.425,0.09])
plt.plot(year, plysical_science, color='blue')
plt.axes([0.525,0.05,0.425,0.9])
plt.plot(year, computer_science, color='red')
plt.show()
#using subplot()
plt.subplot(1,2,1)
plt.plot(year, plysical_science, color='blue')
plt.title('Physical Science')
plt.subplot(1,2,2)
plt.plot(year, computer_science, color='red')
plt.title('Computer Science')
plt.tight_layout()
plt.show()
#using subplot()2
plt.subplot(2,2,1)
plt.plot(year, plysical_science, color='blue')
plt.title('Physical Science')
plt.subplot(2,2,2)
plt.plot(year, computer_science, color='red')
plt.title('Computer Science')
heath=df['Health Professions']
plt.subplot(2,2,3)
plt.plot(year, heath, color='green')
plt.title('Health Professions')
engineering=df['Engineering']
plt.subplot(2,2,4)
plt.plot(year, engineering, color='yellow')
plt.title('Engineering')
plt.tight_layout()
plt.show()
#Control axis extents
#axis([xmin, xmax, ymin, ymax]), .xlim([xmin, xmax]), .ylim((ymin, ymax)) works also
plt.plot(year, engineering, color='black')
plt.title('Engineering')
plt.xlim((1974, 1990))
plt.axis('tight')
plt.axis('equal')
plt.axis('square')
plt.show()
#using xlim() ,ylim()
plt.plot(year, computer_science, color='red')
plt.plot(year, phlysical_science, color='blue')
plt.xlabel('year')
plt.ylabel('degrees award to women(%)')
plt.xlim((1990, 2010))
plt.ylim((10, 50))
plt.title('degrees awarded to women (1990-2010)\n computer_science(red)\nScience(blue)')
plt.show()
